kind: AppHostingConfig
apiVersion: v1
runConfig:
  minInstances: 0
  maxInstances: 10
  concurrency: 80
  cpu: 1
  memoryMiB: 512
env:
  - name: STRIPE_SECRET_KEY
  - name: STRIPE_WEBHOOK_SECRET
  - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
